// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portefeuille.Data;

#nullable disable

namespace Portefeuille.Migrations
{
    [DbContext(typeof(PortefeuilleContext))]
    [Migration("20260228150548_AddPasswordToClient")]
    partial class AddPasswordToClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portefeuille.Models.Actif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portfolio_clientId")
                        .HasColumnType("int");

                    b.Property<string>("Secteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Portfolio_clientId");

                    b.ToTable("Actif");
                });

            modelBuilder.Entity("Portefeuille.Models.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActifId")
                        .HasColumnType("int");

                    b.Property<float>("Montant")
                        .HasColumnType("real");

                    b.Property<float>("Poids")
                        .HasColumnType("real");

                    b.Property<float>("Prixpredit")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ActifId");

                    b.ToTable("Allocation");
                });

            modelBuilder.Entity("Portefeuille.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Budget")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Portefeuille.Models.Donneeboursiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActifId")
                        .HasColumnType("int");

                    b.Property<float>("Cloture")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Volume")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ActifId");

                    b.ToTable("Donneeboursiere");
                });

            modelBuilder.Entity("Portefeuille.Models.Portfolio_client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<float>("RendementPrevu")
                        .HasColumnType("real");

                    b.Property<float>("RisqueVolatilite")
                        .HasColumnType("real");

                    b.Property<float>("ScoreSharp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Portfolio_client");
                });

            modelBuilder.Entity("Portefeuille.Models.Actif", b =>
                {
                    b.HasOne("Portefeuille.Models.Portfolio_client", null)
                        .WithMany("ListeActifs")
                        .HasForeignKey("Portfolio_clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portefeuille.Models.Allocation", b =>
                {
                    b.HasOne("Portefeuille.Models.Actif", null)
                        .WithMany("ListeAllocations")
                        .HasForeignKey("ActifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portefeuille.Models.Donneeboursiere", b =>
                {
                    b.HasOne("Portefeuille.Models.Actif", null)
                        .WithMany("ListeDonneeBoursieres")
                        .HasForeignKey("ActifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portefeuille.Models.Portfolio_client", b =>
                {
                    b.HasOne("Portefeuille.Models.Client", null)
                        .WithMany("ListePortfolio_Client")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portefeuille.Models.Actif", b =>
                {
                    b.Navigation("ListeAllocations");

                    b.Navigation("ListeDonneeBoursieres");
                });

            modelBuilder.Entity("Portefeuille.Models.Client", b =>
                {
                    b.Navigation("ListePortfolio_Client");
                });

            modelBuilder.Entity("Portefeuille.Models.Portfolio_client", b =>
                {
                    b.Navigation("ListeActifs");
                });
#pragma warning restore 612, 618
        }
    }
}
