// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portefeuille.Data;

#nullable disable

namespace Portefeuille.Migrations
{
    [DbContext(typeof(PortefeuilleContext))]
    partial class PortefeuilleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portefeuille.Models.Actif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portfolio_clientId")
                        .HasColumnType("int");

                    b.Property<string>("Secteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actif");
                });

            modelBuilder.Entity("Portefeuille.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Budget")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Portefeuille.Models.Donneeboursiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActifId")
                        .HasColumnType("int");

                    b.Property<float>("Cloture")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Volume")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ActifId");

                    b.ToTable("Donneeboursiere");
                });

            modelBuilder.Entity("Portefeuille.Models.DonneesPredites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActifId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePrediction")
                        .HasColumnType("datetime2");

                    b.Property<float>("PrixPredit")
                        .HasColumnType("real");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonneesPredites");
                });

            modelBuilder.Entity("Portefeuille.Models.Portfolio_client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<double>("CVaR95")
                        .HasColumnType("float");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("NiveauRisque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoidsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RendementPrevu")
                        .HasColumnType("float");

                    b.Property<double>("RisqueVolatilite")
                        .HasColumnType("float");

                    b.Property<double>("ScoreSharp")
                        .HasColumnType("float");

                    b.Property<double>("VaR95")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Portfolio_client");
                });

            modelBuilder.Entity("Portefeuille.Models.Donneeboursiere", b =>
                {
                    b.HasOne("Portefeuille.Models.Actif", null)
                        .WithMany("ListeDonneeBoursieres")
                        .HasForeignKey("ActifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Portefeuille.Models.Portfolio_client", b =>
                {
                    b.HasOne("Portefeuille.Models.Client", "Client")
                        .WithMany("ListePortfolio_Client")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Portefeuille.Models.Actif", b =>
                {
                    b.Navigation("ListeDonneeBoursieres");
                });

            modelBuilder.Entity("Portefeuille.Models.Client", b =>
                {
                    b.Navigation("ListePortfolio_Client");
                });
#pragma warning restore 612, 618
        }
    }
}
